server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Tenta carregar o arquivo, e caso seja uma rota do React (não achou um arquivo físico),
        # redireciona tudo de volta para o index.html, garantindo que o react-router gerencie o roteamento corretamente
        try_files $uri $uri/ /index.html;
    }

    # Desabilitar cache para o html principal
    location ~* \.html?$ {
        root /usr/share/nginx/html;
        expires -1;
    }
}
